// <auto-generated />
using System;
using Cafe.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cafe.Migrations
{
    [DbContext(typeof(ApplicationDbcontext))]
    partial class ApplicationDbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Cafe.Models.Bill", b =>
                {
                    b.Property<string>("BillId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BillId");

                    b.ToTable("Bill");
                });

            modelBuilder.Entity("Cafe.Models.Drink", b =>
                {
                    b.Property<string>("DrinkId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BillId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DrinkName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoLuong")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DrinkId");

                    b.HasIndex("BillId");

                    b.ToTable("Drinks");
                });

            modelBuilder.Entity("Cafe.Models.Drink", b =>
                {
                    b.HasOne("Cafe.Models.Bill", "Bill")
                        .WithMany("Drink")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("Cafe.Models.Bill", b =>
                {
                    b.Navigation("Drink");
                });
#pragma warning restore 612, 618
        }
    }
}
